version: '3.8'

services:
  # docker_test:
  #   container_name: docker_test
  #   image: docker_practice:latest
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - docker_db
  docker_db:
    container_name: poi
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql

  prometheus:
    image: prom/prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus
#      - prom_data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    restart:
      always
    ports:
      - 3000:3000
    depends_on:
      - prometheus